### PR TITLE
0.4.0: Dune + newer angstrom + tests

### PR DESCRIPTION
**Pull request by jonahbeckford**
This PR moves the build system to Dune, makes the code compatible with recent Angstrom, and uses an expect test for test3 and driver/driver.

### CODE REVIEW

**Comment by jdjakub** [comment]
Thank you for your work on this, is there any way I can pass ownership to yourself or declare that I am no longer maintaining this package? It's been so many years since I last touched OCaml and I've been caught off guard by these notifications!

**Comment by jonahbeckford** [comment]
Completely understand. Sure, I can take ownership. I think all you'll need to do is comment your approval in this thread, and then I'll:
a) fork (will become github.com/diskuv/ansi-parse)
b) ask the Opam team to look at this thread and let me switch the source URL for version 0.4.0 onwards

Thanks for developing it; ansi-parse has been very useful!

**Comment by jdjakub** [comment]
I hereby declare my wish for jonahbeckford / diskuv to take ownership of this package :) go ahead and fork, and thanks again.

**Comment by jonahbeckford** [comment]
Thanks Joel! https://opam.ocaml.org/packages/ansi-parse/ has the latest version with all the maintainer bits flipped. If you ever want to step back in, please feel free!

**Pull request closed without merging**
